# Pre-requisites: Python v3.11 / v3.12 / v3.13
# Steps:
# 1. Install LM-Proxy:
#    > pip install lm-proxy
# 2. Install Vertex AI API: 
#    > pip install vertexai
# 3. Install Google Cloud SDK: https://cloud.google.com/sdk/docs/install
# 4. Authenticate with Google Cloud:
#    > gcloud auth application-default login
# 5. Set your Google Cloud project:
#    > gcloud config set project <PROJECT_ID>
# 6. Save this config as `vertex-ai.toml`
# 7. Fill in connections.vertex_ai.google_vertex_project_id and Virtual API Keys for usage in LLM client applications.
# 8. Run LM-Proxy with this config:
#    > lm-proxy --config vertex-ai.toml

[connections]
[connections.vertex_ai]
api_type = "google_vertex_ai"
google_vertex_project_id = "<PROJECT_ID>"
google_vertex_gcloud_auth = true
google_vertex_response_validation = true
model = "gemini-2.5-pro"

[routing]
"gemini-2.5-pro" = "vertex_ai.gemini-2.5-pro"

[groups.default]
# Your Virtual API Keys here
api_keys = [
  "KEY1",
  "KEY2"
]
